#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    #colorscheme = "molokai"
    colorscheme = "gruvbox"
    colorscheme_bg = "dark"
    # file manager pane. Values: vimfiler (default), nerdtree, defx
    #filemanager = "nerdtree"
    enable_vimfiler_gitstatus = true
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_inactive_separator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = true
    enable_neomake = false
    enable_ale = true
    lint_on_the_fly = true
    disabled_plugins = ["neco-look", "floobits"]

# Enable autocomplete layer
[[layers]]
    name = 'autocomplete'
    auto-completion-return-key-behavior = "complete"
    auto-completion-tab-key-behavior = "smart"
[[layers]]
    name = 'checkers'
    show_cursor_error = false
[[layers]]
    name = 'colorscheme'
[[layers]]
    name = 'core#statusline'
[[layers]]
    name = 'debug'
[[layers]]
    name = 'edit'
[[layers]]
    name = 'fzf'
[[layers]]
    name = 'git'
[[layers]]
    name = 'github'
[[layers]]
    name = 'gtags'
[[layers]]
    name = 'lang#c'
[[layers]]
    name = 'lang#elixir'
[[layers]]
    name = 'lang#extra'
[[layers]]
    name = 'lang#go'
[[layers]]
    name = 'lang#haskell'
[[layers]]
    name = 'lang#html'
[[layers]]
    name = 'lang#java'
[[layers]]
    name = 'lang#javascript'
    auto_fix = true
[[layers]]
    name = 'lang#kotlin'
[[layers]]
    name = 'lang#latex'
[[layers]]
    name = 'lang#lisp'
[[layers]]
    name = 'lang#lua'
[[layers]]
    name = 'lang#markdown'
[[layers]]
    name = 'lang#nim'
[[layers]]
    name = 'lang#perl'
[[layers]]
    name = 'lang#python'
    python_file_head = [
        '#!/usr/bin/env python3',
        '# -*- coding: utf-8 -*-',
        '',
        ''
    ]
[[layers]]
    name = 'lang#racket'
[[layers]]
    name = 'lang#rust'
    recommended-style = "enable"
[[layers]]
    name = 'lang#scala'
[[layers]]
    name = 'lang#scheme'
[[layers]]
    name = 'lang#sh'
[[layers]]
    name = 'lang#typescript'
[[layers]]
    name = 'lsp'
    filetypes = [
        'rust',
        'python'
    ]
    [layers.override_cmd]
        rust = ["rust-analyzer"]
[[layers]]
    name = 'shell'
    default_position = 'top'
    default_height = 30
[[layers]]
    name = 'sudo'
[[layers]]
    name = 'test'
[[layers]]
    name = 'tmux'
[[layers]]
    name = 'tools'
[[layers]]
    name = 'ui'
[[layers]]
    name = 'unite'
[[layers]]
    name = 'VersionControl'

[[custom_plugins]]
    name = "airblade/vim-gitgutter"
    merged = true
[[custom_plugins]]
    name = "honza/vim-snippets"
    merged = true
[[custom_plugins]]
    name = "neoclide/coc-rls"
    marged = true
[[custom_plugins]]
    name = "ziglang/zig.vim"
    merged = true
